# Builds src/phoneZones.js from Google's libphonenumber time-zone data (Apache-2.0):
# phone-number prefix (country code + area code) -> IANA time zone, used by src/timezones.js.
# Run: python3 tools/gen_phone_zones.py
import collections, json, os, urllib.request
URL = "https://raw.githubusercontent.com/google/libphonenumber/master/resources/timezones/map_data.txt"
rows = [l.strip().split("|") for l in urllib.request.urlopen(URL).read().decode().splitlines()
        if l.strip() and not l.startswith("#")]
# a prefix can list several zones (e.g. 44 = Guernsey&...&London); pick the one used most across the data
freq = collections.Counter(z for _, zs in rows for z in zs.split("&"))
best = {p: max(zs.split("&"), key=lambda z: freq[z]) for p, zs in rows}
# drop prefixes that just repeat their parent's zone
def parent(p):
    for n in range(len(p) - 1, 0, -1):
        if p[:n] in best: return best[p[:n]]
out = {p: z for p, z in sorted(best.items()) if parent(p) != z}
dest = os.path.join(os.path.dirname(__file__), "..", "src", "phoneZones.js")
with open(dest, "w") as f:
    f.write("// Generated by tools/gen_phone_zones.py from Google libphonenumber (Apache-2.0) - do not edit.\n")
    f.write("// Phone prefix (country code + area code, digits only) -> IANA time zone; look up by longest prefix.\n")
    f.write("export const PHONE_ZONES = " + json.dumps(out, separators=(",", ":")) + ";\n")
print(len(out), "prefixes ->", dest)
