# Portrait topo-map background for the app (same recipe as peterlin.com). Writes src/topoPaths.js.
# Run: python3 tools/gen_topo.py src/topoPaths.js [seed]
import math, random, sys
sys.setrecursionlimit(20000)
random.seed(int(sys.argv[2]) if len(sys.argv) > 2 else 11)
W, H, STEP, NLEV = 1000, 2000, 5, 30
GX, GY = int(W / STEP), int(H / STEP)
FLATS = [.85, .3, .5]   # how much the ground is levelled under each word (big KEN, PETERLIN, small KEN)
RELIEFS = [1.3, .9, 1.3]  # letter height per word, in contour intervals
RELIEF = float(sys.argv[2]) if len(sys.argv) > 2 else 1.3   # letter height, in contour intervals (1.3 => one outline)

# --- terrain (same recipe as before) ---
def lattice(n): return [[random.random() for _ in range(n + 3)] for _ in range(n + 3)]
def sm(t): return t * t * (3 - 2 * t)
octs = [(lattice(60), f, a) for f, a in [(3, 1.0), (6, .5), (12, .25), (24, .12)]]
def vn(g, f, x, y):
    x *= f; y *= f; i, j = int(x), int(y); u, v = sm(x - i), sm(y - j)
    a, b, c, d = g[j][i], g[j][i+1], g[j+1][i], g[j+1][i+1]
    return (a + (b - a) * u) * (1 - v) + (c + (d - c) * u) * v
peaks = [(random.uniform(.1, .9), random.uniform(.1, .9), random.uniform(.08, .2), random.uniform(.6, 1.2)) for _ in range(5)]
def terrain(x, y):
    s = sum(a * vn(g, f, x, y * H / W) for g, f, a in octs)
    return s + sum(h * math.exp(-((x - px) ** 2 + (y - py) ** 2) / (2 * r * r)) for px, py, r, h in peaks)

def dseg(px, py, s):
    ax, ay, bx, by = s; dx, dy = bx - ax, by - ay
    t = max(0, min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - ax - t * dx, py - ay - t * dy)
def bbox_d(x, y, b):
    x0, y0, x1, y1 = b
    return math.hypot(max(x0 - x, 0, x - x1), max(y0 - y, 0, y - y1))

base = [[terrain(i / GX, j / GY) for i in range(GX + 1)] for j in range(GY + 1)]
lo = min(map(min, base)); hi = max(map(max, base)); iv = (hi - lo) / NLEV
vals = base
levels = [lo + iv * (k + .5) for k in range(NLEV + 2)]

def contour(t):
    segs = []
    for j in range(GY):
        for i in range(GX):
            c = [(i, j), (i + 1, j), (i + 1, j + 1), (i, j + 1)]
            v = [vals[j][i], vals[j][i+1], vals[j+1][i+1], vals[j+1][i]]
            pts = []
            for e in range(4):
                a, b = e, (e + 1) % 4
                if (v[a] < t) != (v[b] < t):
                    r = (t - v[a]) / (v[b] - v[a])
                    pts.append((c[a][0] + (c[b][0] - c[a][0]) * r, c[a][1] + (c[b][1] - c[a][1]) * r))
            if len(pts) == 2: segs.append((pts[0], pts[1]))
            elif len(pts) == 4: segs += [(pts[0], pts[1]), (pts[2], pts[3])]
    key = lambda p: (round(p[0], 4), round(p[1], 4))
    ends = {}
    for k, (a, b) in enumerate(segs):
        ends.setdefault(key(a), []).append(k); ends.setdefault(key(b), []).append(k)
    used = [False] * len(segs); lines = []
    for s0 in range(len(segs)):
        if used[s0]: continue
        used[s0] = True; line = list(segs[s0])
        for fwd in (True, False):
            while True:
                p = line[-1] if fwd else line[0]
                n = next((m for m in ends.get(key(p), []) if not used[m]), None)
                if n is None: break
                used[n] = True; a, b = segs[n]; q = b if key(a) == key(p) else a
                line.append(q) if fwd else line.insert(0, q)
        if len(line) > 3: lines.append(line)
    return lines

def chaikin(pts, n=2):
    closed = math.dist(pts[0], pts[-1]) < 1e-6
    for _ in range(n):
        out = [] if closed else [pts[0]]
        for p, q in zip(pts, pts[1:]):
            out += [(p[0]*.75+q[0]*.25, p[1]*.75+q[1]*.25), (p[0]*.25+q[0]*.75, p[1]*.25+q[1]*.75)]
        out.append(out[0] if closed else pts[-1]); pts = out
    return pts
def rdp(pts, eps=.25):
    if len(pts) < 3: return pts
    (ax, ay), (bx, by) = pts[0], pts[-1]; dx, dy = bx - ax, by - ay; L = math.hypot(dx, dy)
    i, dm = 0, 0
    for k in range(1, len(pts) - 1):
        dd = abs(dy * pts[k][0] - dx * pts[k][1] + bx * ay - by * ax) / L if L > 1e-9 else math.dist(pts[k], pts[0])
        if dd > dm: i, dm = k, dd
    if dm <= eps: return [pts[0], pts[-1]]
    return rdp(pts[:i + 1], eps)[:-1] + rdp(pts[i:], eps)

paths = []
for k, t in enumerate(levels):
    d = "".join("M" + " ".join(f"{x*STEP:.0f},{y*STEP:.0f}" for x, y in rdp(chaikin(l), .6)) for l in contour(t))
    if d: paths.append({"d": d, "major": k % 5 == 4})
import json
open(sys.argv[1], "w").write("// Generated by tools/gen_topo.py - do not edit.\n"
    f"export const TOPO_VIEWBOX = '0 0 {W} {H}';\nexport const TOPO_PATHS = " + json.dumps(paths) + ";\n")
